Automattic/VIP-Coding-Standards

- WordPressVIPMinimum/Sniffs/VIP/ErrorControlSniff.php
The wording should try to be less personal, since the fault lies in the code not the person.
> Language change

- WordPressVIPMinimum/Sniffs/VIP/ValidatedSanitizedInputSniff.php
This commit delays the error adding and merges two errors produced by a single sniff into one, if both are about to be triggered.
Fixes #8
> Merging erorr message for non-validated and not-sanitized input variable if both are true

- WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
- WordPressVIPMinimum/ruleset.xml
Since the `get_children` is `setting posts_per_page` to `-1` by default, we should make sure that developers are overriding the default value to something reasonable - eg.: 100
This commit is changing the parent of the `WordPressVIPMinimum_Sniffs_VIP_RestrictedFunctionsSniff` class from `WordPress_AbstractFunctionRestrictionsSniff` to `WordPress_Sniffs_VIP_RestrictedFunctionsSniff` and takes advantage of the inheritance which should allows us to override the original mesages in future.
Further, it is adding the `get_children` group with a message about the default `-1` value for `posts_per_page`.
The changeset also excluded the original WordPress.VIP.RestrictedFunctions since we now have our own with all groups.
Fixes #10
> Report on get_childrent function call due to default -1 for posts_per_page

- WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
The merge of #11 introduced following bugs:
1) Custom reporting on get_children is not properly displayed due to printf not having enough arguments
2) PHPCS is producing duplicate reports for get_children since we are not removing it from the original grop
The PR is addressing the issues above.
> Fixing bugs introduced after merging #11

- WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
The `wpcom_vip_irc_color` function is about to be removed from the codebase via https://github.com/Automattic/vip-go-mu-plugins/pull/467
Let's wait with merging this on the referenced PR.
Fixes #31
> Removing `wpcom_vip_irc_color` from the internal group of restricted functions

- WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
The `flush_rewrite_rules()` should not be used in any normal circumstances in the theme code. This commit adds the function to a new separate group of the Restricted Functions Sniff.
Fixes #30
> Flagging `flush_rewrite_rules` in the Restricted Functions Sniff

- WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
- WordPressVIPMinimum/Tests/Functions/CheckReturnValueUnitTest.inc
- WordPressVIPMinimum/Tests/Functions/CheckReturnValueUnitTest.php
This commit is also adding some extra comments since I found it quite hard to fingure out what's going on
> Adding case for catching non-checking of return value for get_options array_key_exists pair

- WordPressVIPMinimum/Sniffs/VIP/StaticStrreplaceSniff.php
- WordPressVIPMinimum/Tests/VIP/StaticStrreplaceUnitTest.inc
- WordPressVIPMinimum/Tests/VIP/StaticStrreplaceUnitTest.php
- ruleset_test.inc
- ruleset_test.php
eg.: `str_replace( 'foo', 'bar', 'foobar' );`
Fixes #55
> Adding sniff for catching suspicious str_replace calls

- WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
Since the `strip_tags` function is not removing CSS and JS in between the script and style tags, the `wp_strip_all_tags` should be used instead.
Fixes #24
> Flag strip_tags and suggest wp_strip_all_tags instead

- WordPressVIPMinimum/Sniffs/VIP/TaxonomyMetaInOptionsSniff.php
- WordPressVIPMinimum/Tests/VIP/TaxonomyMetaInOptionsUnitTest.inc
- WordPressVIPMinimum/Tests/VIP/TaxonomyMetaInOptionsUnitTest.php
- ruleset_test.inc
- ruleset_test.php
As WordPress provides term meta and as there is a restriction on the size of alloptions on the WordPress.com VIP platform, all term related meta data should be stored in term meta table.
> Addnig basic sniff for catching possible implementation of term meta in options

- WordPressVIPMinimum/Sniffs/Constants/ConstantRestrictionsSniff.php
- WordPressVIPMinimum/Tests/Constants/ConstantRestrictionsUnitTest.inc
- WordPressVIPMinimum/Tests/Constants/ConstantRestrictionsUnitTest.php
This commit adds JETPACK_DEV_DEBUG and WP_CRON_CONTROL_SECRET constants to the list of restricted ones.
In contrast to A8C_PROXIED_REQUEST constant, those two are good to be worked with, just should not be defined.
This new use-case prompted changes in the ConstantRestrictionsSniff itself - new conditions have been added to the code.
Unit tests have been ammended accordingly.
> Add more resticted constants

- WordPressVIPMinimum/Sniffs/Variables/ServerVariablesSniff.php
- WordPressVIPMinimum/Tests/Variables/ServerVariablesUnitTest.inc
- WordPressVIPMinimum/Tests/Variables/ServerVariablesUnitTest.php
Basic Auth should not be set via PHP.
This commit adds new sniff which is producing errors in case it spots `$_SERVER['PHP_AUTH_PW']` in the code.
Unit tests are included.
> Detect Basic Auth implementation in PHP

- WordPressVIPMinimum/Sniffs/VIP/ProperEscapingFunctionSniff.php
- WordPressVIPMinimum/Tests/VIP/ProperEscapingFunctionUnitTest.inc
- WordPressVIPMinimum/Tests/VIP/ProperEscapingFunctionUnitTest.php
Eg.: `<media:content url="`, `data-image-url="`
> Adding open attribute ending with `url` to the ProperEscapingFunction sniff

- WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php
- WordPressVIPMinimum/Tests/JS/HTMLExecutingFunctionsUnitTest.js
- WordPressVIPMinimum/Tests/JS/HTMLExecutingFunctionsUnitTest.php
So far, `.html()` and `.append()`
> Adding sniff for flagging functions which are parsing and executing HTML passed to them.

- WordPressVIPMinimum/Sniffs/VIP/WPQueryParamsSniff.php
- WordPressVIPMinimum/Tests/VIP/WPQueryParamsUnitTest.inc
- WordPressVIPMinimum/Tests/VIP/WPQueryParamsUnitTest.php
Curently:
* `suppress_filters` set to true - fixes #124
* `post__not_in` - fixes #121
Includes unit tests
> Adding sniff for flaggig suspicous WP_Query params.

- WordPressVIPMinimum/Sniffs/VIP/EscapingVoidReturnFunctionsSniff.php
- WordPressVIPMinimum/Tests/VIP/EscapingVoidReturnFunctionsUnitTest.inc
- WordPressVIPMinimum/Tests/VIP/EscapingVoidReturnFunctionsUnitTest.php
> Flag attempt to escape function which prints it's output

- WordPressVIPMinimum/ruleset.xml
As per discussions at the VIP Launch Meetup (Lisbon, Feb 2018), here are some proposed severities for certain sniffs that we feel shouldn't be flagged by default. (The default severity of `PHPCS` is 5.)
> VIP Launch: Add severities for certain sniffs

- WordPressVIPMinimum/ruleset.xml
Per our Launch Meetup @ Lisbon (Feb, 2018), we're changing the messages and the error type of several sniffs.
> VIP Launch: Changing messages and error types for certain sniffs

- WordPress-VIP-Go/ruleset.xml
- WordPressVIPMinimum/ruleset.xml
To preserve the original VIP Minimum ruleset, we're extracting the changes in the original file to a new ruleset, named `WordPress-VIP-Go`.
> Extract ruleset changes in WordPressVIPMinimum to a new ruleset

- WordPressVIPMinimum/Sniffs/Plugins/ZoninatorSniff.php
- WordPressVIPMinimum/Tests/Plugins/ZoninatorUnitTest.inc
- WordPressVIPMinimum/Tests/Plugins/ZoninatorUnitTest.php
Zoninator of v >= 0.8 requires WordPress core REST API, which has to be loaded by `wpcom_vip_load_wp_rest_api()` before the plugin itself. This should remind the reviewers to make sure the core's REST API is being properly loaded.
> Addnig sniff for flagging loading of Zoninator of version >= 0.8

- .gitignore
Operating system and IDE-specific files should be ignored at the global level - see https://gist.github.com/subfuzion/db7f57fff2fb6998a16c .
While `phpcs.xml.dist` does not (yet) exist, `phpcs.xml` and `.phpcs.xml` are meant to be local overrides, so should not be in version control anyway.
> Update .gitignore to ignore vendor/ and some files

- WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php
changed the html string concatenation message to mention security, dom node construction, and templating languages, as well as making the two messages consistent
closes #191
> changed the html string concatenation message

- README.md
The public facing WordPress.com VIP documentation has been updated to include much more detailed install instructions. This commit updates the `README.md` to link to that documentation. 
Closes https://github.com/Automattic/vip-issues/issues/168
> Update Readme link to latest VIP documentation

- WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php
- WordPressVIPMinimum/Tests/Functions/DynamicCallsUnitTest.inc
- WordPressVIPMinimum/Tests/Functions/DynamicCallsUnitTest.php
Dynamic calls to certain functions are not allowed in PHP 7.1 and forwards. This sniff will find some of these.
http://php.net/manual/en/migration71.incompatible.php
> Add new sniff to find dynamic calls to functions

- WordPressVIPMinimum/Sniffs/VIP/RobotstxtSniff.php
- WordPressVIPMinimum/Tests/VIP/RobotstxtSniff.inc
- WordPressVIPMinimum/Tests/VIP/RobotstxtSniff.php
Since we need to flush NginX cache in production in order to make the change taking effect after the code is deployed, we should remind this to deployers and PHPCS is an easy enough path for surfacing this information.
Fixes #25
> Flag `do_robotstxt` action callback

- WordPress-VIP-Go/ruleset.xml
```
ERROR: Referenced sniff "WordPress.WP.GlobalVariables.OverrideProhibited" does not exist
```
This should resolve it.
> Fix error of WordPress.WP.GlobalVariables.OverrideProhibited not existing

- WordPressVIPMinimum/Sniffs/Functions/CreateFunctionSniff.php
- WordPressVIPMinimum/Tests/Functions/CreateFunctionSniff.inc
- WordPressVIPMinimum/Tests/Functions/CreateFunctionSniff.php
create_function() is deprecated as of PHP 7.2.0 (see: http://php.net/manual/en/function.create-function.php). This sniff will generate an error when call to that function is detected.
> Sniff to detect create_function()

- WordPressVIPMinimum/Sniffs/SVG/HTMLCodeSniff.php
- WordPressVIPMinimum/Tests/SVG/HTMLCodeSniff.php
- WordPressVIPMinimum/Tests/SVG/HTMLCodeSniff.svg
- WordPressVIPMinimum/ruleset.xml
Look for <?php and <?= in SVG files, and give a warning when that happens.
> Add SVG files sniff for PHP openings

- .travis.yml
- CONTRIBUTING.md
- WordPress-VIP-Go/ruleset.xml
- bin/integration-test
- bin/php-lint
- bin/phpcs
- bin/unit-tests
- bin/xml-lint
- composer.json
There are two commits in this PR:
1. Introduce re-usable bash scripts, and have Composer and Travis use them.
1. Split the updated Travis config to use Build Stages.
The first commit also incorporates PR #208, so that can be closed unmerged once this is merged.
A typical Travis config file is a YAML file containing shell scripts. This makes it a little painful to manage:
- mixing YAML syntax requirements and shell syntax in the same lines takes unnecessary brain power to follow, and a competent IDE to highlight correctly.
- scripts are not reusable locally, meaning the logic has to be reimplemented manually.
- scripts are not fully documented, making much of the Travis config tricky for new developers to understand.
Within the Travis config file, I identified five main non-trivial tasks: …
> Introduce reusable bash scripts

- .travis.yml
PHPUnit 6 was needed when the lowest supported/tested version of PHPCS was 3.1.0.
PHPCS 3.2.3 (which is the currently lowest supported version) claims to support PHPUnit 7, so we can let the Composer constraint of `"phpunit/phpunit": "*"` dictate which version of PHPUnit is installed and used when running the test, depending on the version of PHP being used.
Currently:
| PHP Version 	| PHPUnit Version 	|
|-------------	|-----------------	|
|     5.6     	|      5.7.27     	|
|     7.0     	|      6.5.12     	|
|     7.1     	|      7.3.4      	|
|     7.2     	|      7.3.4      	|
|   Nightly   	|      7.3.4      	|
Also adds explicit stage naming so that we avoid a situation like de3061d654cc4c46bc6a79ad996b2d947312dff1.
> Travis: Remove PHPUnit 6 workaround

- WordPressVIPMinimum/ruleset.xml
As per #53, `var_dump()` and `var_export()` should be the same type/severity since they are similar.  Removing `var_dump()` from the ruleset restores it back to the default "Warning" level.
> Remove `var_dump()` from ruleset 

- WordPress-VIP-Go/ruleset.xml
`Variable assignment found within a condition. Did you mean to do a comparison?`
I find that this flags a false positive 99.9999% of the time since it's more of a...coding style? Would be nice to remove altogether for noise purposes on Go.
> Downgrade severity of Variable assignment condition rule

- WordPress-VIP-Go/ruleset.xml
- WordPressVIPMinimum/Sniffs/VIP/PHPFilterFunctionsSniff.php
- WordPressVIPMinimum/Tests/VIP/PHPFilterFunctionsUnitTest.inc
- WordPressVIPMinimum/Tests/VIP/PHPFilterFunctionsUnitTest.php
Per #222, this detects if there is an invalid filter ID passed into the PHP filter_* functions or none passed in for `filter_var`, `filter_input`, `filter_var_array`, `filter_input_array`.
@GaryJones Let me know if you think it's better to check against a whitelist for an invalid filter.
> Detect filter not passed in PHP filter_* functions

- WordPressVIPMinimum/ruleset.xml
The WordPress.com VIP team moved the coding standards documentation around, since they now have different documents for their different platforms:
- [WPCOM platform](https://lobby.vip.wordpress.com/wordpress-com-documentation/code-review-what-we-look-for/) (only available to those with VIP Lobby access)
- [VIP-Go platform](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)
This updates the out of date references for links to the Lobby.
See https://github.com/Automattic/vip-issues/issues/160
> Docs: Update VIP link references

- WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
- WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.inc
- WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.php
Per #239, we should never be calling `opcache_reset()`.
> Add opcache_reset() to list of restricted functions.

- WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
- WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.inc
- WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.php
Per #156, ACF's `the_field()` and `the_sub_field()` do not escape outputted.
> Add ACF templating function to warnings

- WordPress-VIP-Go/ruleset.xml
- WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
- WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.inc
- WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.php
This PR resolves #252.
* Since the sniff for `WordPressVIPMinimum.VIP.RestrictedFunctions.get_page_by_path_get_page_by_path` was being called by the parent class function:
https://github.com/Automattic/VIP-Coding-Standards/blob/f8cd4b5be5b70de1ae009d75404cea205cec0839/WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php#L24
I ended up removing the dependency of the [already deprecated since WPCS 1.0](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/1cb6a74615be51390776c3c22438c21b010c1737/WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php#L1) `WordPress.VIP.RestrictedFunctions` sniff (see #187) and refactored it into the (no-longer child) `WordPressVIPMinimum.VIP.RestrictedFunctions` sniff: https://github.com/Automattic/VIP-Coding-Standards/blob/f8cd4b5be …
> Remove get_page_by_path sniff and refactor RestrictedFunctions sniff without parent

- WordPress-VIP-Go/ruleset.xml
- WordPressVIPMinimum/Sniffs/Functions/StripTagsSniff.php
- WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
- WordPressVIPMinimum/Tests/Functions/StripTagsUnitTest.inc
- WordPressVIPMinimum/Tests/Functions/StripTagsUnitTest.php
- WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.inc
- WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.php
- WordPressVIPMinimum/ruleset.xml
This resolves #133.
What this PR does:
* add a StripTags sniff
* remove the WordPress.AlternativeFunctions rules for strip tags
* remove strip_tags from RestrictedFunctions sniff
> Add StripTags sniff and amend rulesets and existing sniffs

- WordPressVIPMinimum/Sniffs/VIP/WPQueryParamsSniff.php
Fixes #277.
Also:
* adds supporting documentation links in comments per platform.
* adds documentation link directly in error message for `post__not_in` warning.
> Fix typo in error message for WordPressVIPMinimum.VIP.WPQueryParams.suppressFilters

- WordPress-VIP-Go/ruleset.xml
- WordPressVIPMinimum/Sniffs/Filters/RestrictedHookSniff.php
- WordPressVIPMinimum/Tests/Filters/RestrictedHookUnitTest.inc
- WordPressVIPMinimum/Tests/Filters/RestrictedHookUnitTest.php
Fixes #45.  
Also changes RestrictedHookSniff to have different error types on a hook basis.  I chose a severity of 5 since it matches the other performance issues flagged with a warning of 5.
> Flag filters for changing timeouts

- WordPressVIPMinimum/Sniffs/Filters/AlwaysReturnSniff.php
- WordPressVIPMinimum/Tests/Filters/AlwaysReturnUnitTest.inc
- WordPressVIPMinimum/Tests/Filters/AlwaysReturnUnitTest.php
Now properly catches filter callbacks that don't `return` _anywhere_ inside the function body
Fixes #290
> Fix AlwaysReturnSniff for missing return statement

- WordPressVIPMinimum/Sniffs/Classes/RestrictedExtendClassesSniff.php
- WordPressVIPMinimum/Sniffs/Filters/RestrictedHookSniff.php
- WordPressVIPMinimum/Sniffs/Functions/StripTagsSniff.php
- WordPressVIPMinimum/Sniffs/JS/WindowSniff.php
- WordPressVIPMinimum/Sniffs/Variables/ServerVariablesSniff.php
- WordPressVIPMinimum/Tests/Filters/AlwaysReturnUnitTest.php
- WordPressVIPMinimum/Tests/Filters/RestrictedHookUnitTest.php
- WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php
- bin/phpcs
Fixes whitespace-only violations in our own sniff and test code.
Stops ignoring warnings on exit when running PHPCS against our own code, so that these can't slip in again.
> Fix PHPCS violations in VIPCS

- composer.json
The `@phpcs` Composer script takes the longest to execute, and is less critical than the integration and unit tests, so move the `@phpcs` to be the last item in the `test` Composer script.
> Change Composer test script order

- CHANGELOG.md
First pass at a change log, for 0.4.0.
See #233.
> Add change log (starting at 0.4.0)

- .phpcs.xml.dist
We require PHP 5.6 or above (in `composer.json`), so we only need to check our code is compatible with PHP 5.6 and above.
Fixes #305
> PHPCS: Bump testVersion to match PHP requirement

- WordPressVIPMinimum/Sniffs/Filters/AlwaysReturnSniff.php
- WordPressVIPMinimum/Sniffs/Functions/CreateFunctionSniff.php
- WordPressVIPMinimum/Sniffs/VIP/MergeConflictSniff.php
- WordPressVIPMinimum/Sniffs/VIP/RobotstxtSniff.php
Remove use of PHPCS 2.x class names in favour of the namespaced classes from PHPCS 3.x.
Fixes #300.
> Use PHPCS 3.x namespaced classes

- WordPressVIPMinimum/Sniffs/VIP/FetchingRemoteDataSniff.php
> FetchingRemoteDataSniff: Fix typo of missing "n" in "Unknown".

- .phpcs.xml.dist
- .travis.yml
- WordPress-VIP-Go/ruleset.xml
- WordPressVIPMinimum/ruleset.xml
- bin/xml-lint
As of PHPCS 3.2.0, PHPCS includes an XSD schema for rulesets which defines what can be used in the XML ruleset file.
In PHPCS 3.3.0 a new array format for properties was introduced and as of PHPCS 3.3.2, the new array format is now also covered by this schema.
This commit:
- Adds the schema tags to the `ruleset.xml` files, and the VIPCS native `.phpcs.xml.dist` file.
- Adds validation against the schema for the `ruleset.xml` files to the Travis build.
- Fixes invalid markup in the `WordPress-VIP-Go` ruleset flagged by the validation procedure.
Note:
The schema used in the tags points to the online schema in PHPCS master for two reasons:
1. While VIPCS has a minimum requirement of PHPCS 3.2.3, the schema in PHPCS master contains the changes which were made in PHPCS 3.3.2, so we can safely …
> PHPCS: Add XSD reference and validate rulesets

- WordPressVIPMinimum/Sniffs/Filters/AlwaysReturnSniff.php
- WordPressVIPMinimum/Tests/Filters/AlwaysReturnUnitTest.inc
- WordPressVIPMinimum/Tests/Filters/AlwaysReturnUnitTest.php
Fixes #293.
* If no return, it will trigger an error instead of a warning.
* If a callback arg is being passed in by reference, it should not trigger.
> AlwaysReturnSniff will trigger errors unless callback args is pass by reference

- composer.json
https://github.com/Dealerdirect/phpcodesniffer-composer-installer/releases/tag/v0.5.0 was released back in October, with a few fixes and improvements.
Fixes #314.
> Switch to phpcodesniffer-composer-installer v0.5.0

- composer.json
Although we were suggesting the `dealerdirect/phpcodesniffer-composer-installer` Composer plugin during the `composer install`, it wasn't actually being used in VIPCS.
By using it, the `post-install-cmd` and `post-update-cmd` scripts are eliminated, and the manual `install-codestandards` script is updated to be available should a `composer ... --no-plugins` flag be used, and instead let the Composer plugin handle the registration.
Fixes #317
> Use phpcodesniffer-composer-installer plugin

- .travis.yml
Expand on the note to explain _why_ we can only use `dev-master` for PHPCS for latest PHP versions.
Fixes #304
> Travis: Add PHP 7.3 testing

- WordPressVIPMinimum/Sniffs/AbstractVariableRestrictionsSniff.php
- WordPressVIPMinimum/Sniffs/VIP/RestrictedVariablesSniff.php
WPCS 1.0 marked the `AbstractVariableRestrictionsSniff` as deprecated, since the only sniffs using it were from the `WordPress.VIP` category of sniffs, which were themselves deprecated.
WPCS 2.0 removes the `AbstractVariableRestrictionsSniff`, so this copies it into VIPCS where we can maintain and improve it.
It is currently only extended by the RestrictedVariablesSniff class.
Fixes #325.
Only change from original `AbstractVariableRestrictionsSniff` is removal of `@since` tags, slight tidying of DocBlocks, conversion to short array syntax, change of namespace & import statement.
> Copy AbstractVariableRestrictionsSniff from WPCS

- WordPress-VIP-Go/ruleset.xml
- Update rules with violation code references, after changes for [inconsistent](https://github.com/Automattic/VIP-Coding-Standards/pull/315), [unusual](https://github.com/Automattic/VIP-Coding-Standards/pull/312) and [duplicate](https://github.com/Automattic/VIP-Coding-Standards/pull/311) violation codes.
- Remove redundant rule properties i.e. severity level, type and message that matched the original sniff / parent standard.
- Order rules in each section alphabetically, to make it easier to read and maintain.
- Other fixes, such as referencing deprecated WPCS sniffs, or non-existent violation codes.
- Add comment to clarify that the `ruleset.xml` should only contain the changes from the defaults.
Fixes #333.
May need rebasing after #332 is merged.
Alas, I didn't think to do commits …
> Update WordPress-VIP-Go ruleset file

- WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
Closes https://github.com/Automattic/VIP-Coding-Standards/issues/334
The rule name seems a bit convoluted, but I'm not sure if changing that is a good idea: https://github.com/Automattic/VIP-Coding-Standards/blob/b46ec66b8899d6ca8f83e9b0e70062ed6409c184/WordPress-VIP-Go/ruleset.xml#L128
> Remove non-existing function: url_to_post_id

- WordPressVIPMinimum/ruleset.xml
Currently at a warning level.  Fixes #338.
> Upgrade exec() and shell_exec() to be flagged as error

- WordPress-VIP-Go/ruleset.xml
- WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
- WordPressVIPMinimum/ruleset.xml
In the `RestrictedFunctionsSniff`, we had `fwrite` and `file_put_contents` which was duplicating the effort of WPCS and producing duplicate error messages:
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/ab999048a69e8614103af3fad4ccf4f124b9f520/WordPress/Sniffs/WP/AlternativeFunctionsSniff.php#L91-L92
This PR:
* removes it from the `RestrictedFunctionsSniff`
* removed the duplicate VIPCS reference in the `WordPress-VIP-Go` ruleset for `fwrite`
* changes the reference to use WPCS for `file_put_contents` in the `WordPress-VIP-Go` ruleset
* adds both WPCS references to `WordPressVIPMinimum` ruleset for `fwrite` and `file_put_contents`
* changes the error message for filesystem write sniffs.
> Remove fwrite and file_put_contents from RestrictedFunctions

- composer.json
PHPCS [supports](https://github.com/squizlabs/PHP_CodeSniffer/blob/49a3e26aa3aa042fece78b0061ba46ccc5f51e76/composer.json#L34) up to PHPUnit 7, but VIPCS was [pulling in `*`](https://github.com/Automattic/VIP-Coding-Standards/blob/5a581766b5c7c2a6e0120e6f94723c6f85a02e20/composer.json#L25), which at this time resolves to 8.0.1.
This caused an error in Travis jobs for PHP 7.2, 7.3 and nightly:
> PHP Fatal error:  Declaration of PHP_CodeSniffer\Tests\Core\File\FindEndOfStatementTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /home/travis/build/Automattic/VIP-Coding-Standards/vendor/squizlabs/php_codesniffer/tests/Core/File/FindEndOfStatementTest.php on line 203
[PHPUnit 8.0 dropped support for PHP …
> Travis: Restrict PHPUnit versions to match PHPCS

- WordPress-VIP-Go/ruleset.xml
This PR:
* Removes `WordPress.WP.AlternativeFunctions.file_system_read_file_get_contents` because it is already excluded in the `WordPressVIPMinimum` ruleset (which this ruleset inherits from)
https://github.com/Automattic/VIP-Coding-Standards/blob/5a581766b5c7c2a6e0120e6f94723c6f85a02e20/WordPressVIPMinimum/ruleset.xml#L138
* Removes the custom message for `WordPressVIPMinimum.Functions.RestrictedFunctions.get_adjacent_post_get_adjacent_post` because the sniff already has a similar one in place:
https://github.com/Automattic/VIP-Coding-Standards/blob/5a581766b5c7c2a6e0120e6f94723c6f85a02e20/WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php#L165
* Adds `WordPressVIPMinimum.Functions.RestrictedFunctions.get_adjacent_post_get_previous_post`, …
> Re-organize WordPress-VIP-Go ruleset for consistency

- WordPress-VIP-Go/ruleset.xml
Short echo tags `<?=` has been constantly on since PHP 5.4. There is no fundamental reason why these should be disallowed.
This still forbids them for `WordPressVIPMinimum`, and it still forbids short open tags `<?` for both platforms.
I'd be open in removing them for `WordPressVIPMinimum` as well if needed.
WIP, since it needs ruleset tests to be updated.
> WIP: Silence Short Echo Tag on VIP Go

- WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
When performing a refactor of the sniffs here - 60283aa - it appears that one $tokens variable was not updated to $this->tokens.
Hat-tip to @kjbenk for reporting it.
Fixes #389.
> Fix undefined variable: tokens

- README.md
Since this doesn't work against master of the WordPress Coding Standards, add some language to the README to help people get it working.
> Update the readme a bit to add language around installing compatible WPCS

- tests/RulesetTest.php
We expect two errors on line 2 of the code block below:
```
if ( isset( $_POST['nonce'] ) && wp_verify_nonce( sanitize_text_field( $_POST['nonce'] ) ) ) {
bar( $_POST['foo2'] ); // Error x 2.
$foo2 = isset( $_POST['foo2'] ) ?? foo( sanitize_text_field( $_POST['foo2'] ) ); // Ok - exclude WordPress.Security.ValidatedSanitizedInput.MissingUnslash.
}
```
But it doesn't find it in ruletest:
```
Expected 2 errors, found 1 on line 2.
```
This is because we are incrementing after assignment and thus, we lose the true value since it continues to be overwritten and it stays at `1` forever.  
We should increment prior to assignment.
> Ruleset test: Fix bug where it doesn't catch proper number of errors/warnings on a line basis

- .phpcs.xml.dist
The PHPCS check of our VIPCS code passes without needing the exclusion of the `WordPress.CodeAnalysis.AssignmentInCondition.FoundInWhileCondition` check.
> Remove a WordPress-Extra exclusion

- CONTRIBUTING.md
The default branch has been changed from `master` to `develop`, as we move to a _git-flow_ workflow, so this updates the docs.
> Docs: Update notes on ongoing development

- WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
Encourage developers to switch to the VIP version of the function by telling them a benefit.
Message pulled from [here](https://github.com/Automattic/vip-go-mu-plugins/blob/50c25c02753d7ba46a168b5206775cdecfcade57/vip-helpers/vip-utils.php#L721).
Fixes #436.
> wp_remote_get: expand on message

- WordPress-VIP-Go/ruleset.xml
It's not clear why this violation is marked as an Error for VIP Go ruleset, when none of the other HTMLExecutingFunctions are left as their default of Warnings.
Since the best the Sniff can do is provide warnings when a variable is used (though that variable may already be safe, and not contain user input), then it would seem odd to change just one function call to an Error for VIP Go.
> append: Remove error for use of append in VIP Go

- WordPressVIPMinimum/ruleset-test.inc
- WordPressVIPMinimum/ruleset.xml
Note that `composer test` was failing for me on the `master` branch locally due to some issues unrelated to the code here, so I'd expect that there is some other work that needs to be done to fix the tests. When I ran the tests individually, the short array syntax sniff was flagging also, which is likewise unrelated to the changes in this PR.
> Use new sniff WordPress.DateTime.RestrictedFunctions

- WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
- WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.inc
- WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.php
On VIP there is an alternative which should be used for caching
`wpcom_vip_get_page_by_path()` make developers aware of this by warning
of usage of `get_page_by_path()`.
> Add get_page_by_path() warning to VIP restricted function sniffs.

- .phpcs.xml.dist
- WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php
[Tests are currently failing](https://travis-ci.org/Automattic/VIP-Coding-Standards/jobs/615177473?utm_medium=notification&utm_source=github_status) because of the rule `Generic.Arrays.DisallowShortArraySyntax.Found` and it looks like the formatting in `DynamicCallsSniff` is also failing tests for `WordPress.Arrays.ArrayKeySpacingRestrictions.TooMuchSpaceAfterKey`.
> Allow for short array syntax

- WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php
- WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
- WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.inc
- WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.php
> RestrictedFunctions: Add stats_get_csv()

- .travis.yml
- composer.json
[WPCS 2.3.0](https://github.com/WordPress/WordPress-Coding-Standards/releases/tag/2.3.0) and [PHPCS 3.5.5](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.5.5) have been out for a little while.
The Composer plugin has only been out a week, but has tested fine, and is a development dependency only anyway (until WPCS 3.0.0 is pulled in).
> Dependencies: Update versions

- .travis.yml
By default, our tests on PHP 8 nightly use PHPUnit 5.2.7, which includes calls to `each()`, which was removed in PHP 8, and therefore fails.
By ignoring the platform requirements, then PHPUnit 7 should be installed, as that's the highest version supported in the `composer.json` constraints.
All credit to @jrfnl for the same work she did on WPCS.
> Travis: Use PHPUnit 7 with PHP 8

- .travis.yml
- README.md
- composer.json
PHP 5.4 is the minimum that PHPCS and WPCS support, so it would be nice to be able to say VIPCS supports the same minimum version of PHP.
As much as I'd love to use some PHP 7-only syntax in sniffs, that doesn't seem like a good enough reason to limit what versions of PHP we support for using this tool (it doesn't affect what versions of PHP that themes and plugins use of course).
> Travis: Expand supported PHP down to 5.4

- CHANGELOG.md
- README.md
Once merged, ensure the branch is restored, since it's also used for #488.
> Docs: Changelog for 2.1.0

- .gitattributes
Exclude files from release archives.
This will also make them unavailable when using Composer with `--prefer-dist`.
If you develop for VIPCS using Composer, use `--prefer-source`.
See https://blog.madewithlove.be/post/gitattributes/
> chore: Add `.gitattributes` file

- .phpcs.xml.dist
1. According to the `composer.json` file, the minimum supported PHP version is PHP 5.4, so PHPCompatibility should be set to check for that, not for PHP 5.6 and up.
2. Excluding a complete sniff instead of including it twice and excluding the single errorcode.
This is more efficient as it prevents the sniff from running completely instead of letting the sniff run and silencing the error at the moment it is being thrown.
> CS ruleset: minor tweaks

- tests/RulesetTest.php
This is probably just needed for me, but when running the ruleset tests locally on Windows, they wouldn't run and would show a `'$PHPCS_BIN' is not recognized as an internal or external command,
operable program or batch file.` error.
By not relying on (linux) CLI variable expansion, but expanding the variable to its real path value and using the literal value within the script, the tests can be run on Windows too.
(and yes, I'm making sure my local environment is all set up correctly for working with VIPCS ;-) )
> RulesetTest: fix compatibility with Windows

- WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
- WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.inc
- WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.php
... and `Walker::paged_walk()`.
The method signature of both the `Walker::walk()` method as well as the `Walker::paged_walk()` method were changed in WordPress 5.3 to make the variadic nature of the allowed arguments explicit.
This change updates the sniff to verify the signature of these methods in child classes against the new method signature as it is in WordPress Core.
Refs:
* https://make.wordpress.org/core/2019/10/09/wp-5-3-introducing-the-spread-operator/
* https://core.trac.wordpress.org/changeset/46442
Fixes #448
Note: I've pointedly ignored everything else which could be improved in this sniff and just focused on getting this particular issue fixed for now.
> DeclarationCompatibility: fix incorrect signature check for `Walker::walk()`

- WordPressVIPMinimum/ruleset-test.inc
- bin/ruleset-tests
- tests/RulesetTest.php
The builds on PHP 5.4, 5.5 and 5.6 should have been failing on the ruleset test for a while now, but aren't.
Example: https://travis-ci.org/github/Automattic/VIP-Coding-Standards/jobs/710513865#L311-L315
What is happening here is that when several commands are run via a script, Travis will only look at the exit code of the _last_ script to decide whether the build should be failed or not.
This means that failures from the `WordPressVIPMinimum` ruleset test were never failing the build as they were hidden by a passing ruleset test for the `WordPress-VIP-Go` ruleset.
By chaining the commands together, the exit codes of both commands are taken into account when determining whether the build should be failed or not.
Ok, this is a fun one.
Line 5 of the ruleset-test is not supposed to error. …
> WordPressVIPMinimum: fix the failing ruleset test & let Travis show failures

- tests/RulesetTest.php
... instead use the PHP version used when this script was called.
`shell_exec()` opens a new process and that process does not inherit the PHP executable which was used to run the tests, but uses the system default PHP version instead, which means that the PHPCS command may run on a different PHP version than the tests.
The current solution is a simple one and not exhaustive, but should suffice in most cases.
If a more complex/more comprehensive solution is desired, I'd recommend using the `PhpExecutableFinder` from the `Symfony\Process` package.
_Context: I needed this fix to be able to properly investigate #485 _
> RulesetTest: don't use the system default version of PHP

- tests/bootstrap.php
* Remove some code duplication by using an interim variable.
* Check that the PHPCS native bootstrap file can be found.
* Remove the question about using PHPCS 3.x. That's not in question anymore.
* Fix the link to the contributing.md file - this was previously pointing to the WPCS one.
* Set the `PHPCS_IGNORE_TESTS` environment variable automatically to the correct value to prevent running tests from other standards.
> Test bootstrap: various minor tweaks

- WordPressVIPMinimum/Tests/Variables/RestrictedVariablesUnitTest.inc
- WordPressVIPMinimum/Tests/Variables/RestrictedVariablesUnitTest.php
* The namespace of the test file was not for VIPCS.
* Update the inline `exclude` property setting syntax.
> Variables/RestrictedVariables: fix namespace of unit test file + fix test

- WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
- WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.inc
Quick fix for false positives on class instantiation.
First new unit test was already ok, second unit test would previously fail.
Fixes #469
Notes:
* I've pointedly ignored everything else which could be improved in this sniff and just focused on getting this particular issue fixed for now.
* The parent `is_targetted_token()` method has diverged quite a bit from what is in the method in this class.
Rather than address this now, I propose to address this once the improved/namespace and use context aware abstracts in PHPCSUtils are available as this sniff would benefit from switching over to such abstract.
> Functions/RestrictedFunctions: fix false positive on class instantiation

- WordPress-VIP-Go/ruleset-test.inc
- WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
- WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.inc
- WordPressVIPMinimum/ruleset-test.inc
The functions in the `config_settings` group were using a unicode `_`, not the ascii `_`, so these would never match the PHP native `opcache_*` functions they were intended to match.
As the same unicode character was used in the applicable unit tests and ruleset tests, the bug was never reported as a test failure.
Related to #518 (sniff review)
> RestrictedFunctions: fix false negative - functions in `config_settings` would never match

- WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php
- WordPressVIPMinimum/Tests/Hooks/PreGetPostsUnitTest.inc
This adds a unit test which results in the error as reported in issue #499 and fixes the error properly.
The error was caused by the presumption in the code that if a check for `is_main_query` has a scope condition which is a `closure`, that the `closure` is the callback in the hook function call and that therefore the outer parenthesis (those of the function call) should be disgarded and the next parenthesis will be the ones for the `if` statement which will always have a scope opener and closer.
Now read the above sentence again and count the number of assumptions in that statement ;-)
Either way, the fix I've now added should stabilize this part of the code.
Fixes #499
---
[Edit] I've added a second commit to the code after seeing the actual code which was triggering the error.
--- …
> PreGetPosts: improve the isEarlyMainQueryCheck() method

- WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
- WordPressVIPMinimum/Tests/Hooks/AlwaysReturnInFilterUnitTest.inc
- WordPressVIPMinimum/Tests/Hooks/AlwaysReturnInFilterUnitTest.php
As VIPCS is currently using WPCS 2.x, we can use the WPCS `Sniff::find_array_open_close()` method to get the opener/closer for an array independently of the type of array (long/short).
Once VIPCS implements PHPCSUtils, this method call should be swopped out for the PHPCSUtils `Arrays::getOpenClose()` method.
Addresses #358 for the `AlwaysReturnInFilter` sniff.
Includes unit tests.
> Hooks/AlwaysReturnInFilter: add support for hook-ins using short arrays

- WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php
- WordPressVIPMinimum/Tests/Hooks/PreGetPostsUnitTest.inc
- WordPressVIPMinimum/Tests/Hooks/PreGetPostsUnitTest.php
As VIPCS is currently using WPCS 2.x, we can use the WPCS `Sniff::find_array_open_close()` method to get the opener/closer for an array independently of the type of array (long/short).
Once VIPCS implements PHPCSUtils, this method call should be swopped out for the PHPCSUtils `Arrays::getOpenClose()` method.
Addresses #358 for the `PreGetPosts` sniff.
Includes unit tests.
> Hooks/PreGetPosts: add support for hook-ins using short arrays

- WordPress-VIP-Go/ruleset-test.inc
- WordPressVIPMinimum/Sniffs/AbstractVariableRestrictionsSniff.php
- WordPressVIPMinimum/Tests/Variables/RestrictedVariablesUnitTest.inc
- WordPressVIPMinimum/Tests/Variables/RestrictedVariablesUnitTest.php
Disregard when the existence of a restricted variable is being checked. This uses the upstream WPCS `Sniff::is_in_isset_or_empty()` method.
This means that variables will not be reported as "used" when they are wrapped in a call to:
* `isset()`
* `empty()`
* `array_key_exists()`
This also means that the `if ( isset( $_SERVER['REMOTE_ADDR'] ) ) {` test on line 13 will no longer report a warning.
As `$_SERVER['REMOTE_ADDR']` was then no longer tested for and `$_SERVER['HTTP_USER_AGENT']` was being tested twice (line 14 and line 28), I've changed the occurrence on line 14 to use `$_SERVER['REMOTE_ADDR']` to make sure both are still tested.
Includes additional unit test for the case as reported by the op.
Fixes #568
> RestrictedVariables: don't report on "use" in `isset()`

- composer.json
We don't require or require-dev any packages that are not stable, so no need to continue allowing RC at this time.
Fixes #562.
> Composer: Change minimum stability to stable

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/release-template.md
- README.md
Documenting our release process, and updating the release template slightly.
> Docs: Update notes for releasing

- WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
- WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.inc
- WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.php
Recognise that a form `action` attribute expects to have a URL value, and therefore expected to be escaped with `esc_url()`, rather than `esc_attr()`.
Fixes #554
> ProperEscaping: Fix message for action attribute

- CHANGELOG.md
GitHub usernames are in non-case-sensitive alphabetical order.
Moving props to be for the release, rather than individual change entries make them cleaner to read. From 2.2.0 onwards, we'll be linking through to the relevant PR, so it will be easier to see who specifically helped with what, though the comparison links show all of the PRs anyway.
Props include those who also just did a merge commit, since they would hopefully have reviewed the change as well anyway.
> Docs: Add comparisons and props for old versions

- .travis.yml
The builds are failing a little too often for my taste on the below error.
```
[Composer\Downloader\TransportException]
Peer fingerprint did not match
```
I'm prefixing the `composer install` commands now with `travis_retry` in an attempt to get round this problem.
Ref:
* https://docs.travis-ci.com/user/common-build-problems/#timeouts-installing-dependencies
> Travis: retry composer install on failure

- WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
- WordPressVIPMinimum/Tests/Hooks/AlwaysReturnInFilterUnitTest.inc
- WordPressVIPMinimum/Tests/Hooks/AlwaysReturnInFilterUnitTest.php
If a filter is defined in the constructor of an abstract class, and uses an abstract method as its callback, relying on implementing classes to define the return value, the `WordPressVIPMinimum.Hooks.AlwaysReturnInFilter.MissingReturnStatement` sniff causes phpcs to crash.
This PR adds a unit test to confirm the issue, and implements a fix using the same code that is used by phpcs itself.
Fixes #580
> Ignore return values when a filter callback is abstract

- WordPressVIPMinimum/Sniffs/Compatibility/ZoninatorSniff.php
- WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
- WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
- WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php
- WordPressVIPMinimum/Sniffs/Performance/CacheValueOverrideSniff.php
- WordPressVIPMinimum/Sniffs/Performance/FetchingRemoteDataSniff.php
- WordPressVIPMinimum/Sniffs/Performance/TaxonomyMetaInOptionsSniff.php
- WordPressVIPMinimum/Sniffs/Security/ExitAfterRedirectSniff.php
- WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
- WordPressVIPMinimum/Sniffs/Security/StaticStrreplaceSniff.php
The `register()` method tells PHPCS which tokens a sniff is listening for.
A number of sniffs were currently registering the [`Tokens::$functionNameTokens`](https://github.com/squizlabs/PHP_CodeSniffer/blob/9cce6859a595b3fa77fc823d9b0d451951dcf9d2/src/Util/Tokens.php#L570-L583) array.
In all cases, these sniffs were only looking for specific function calls, and in most cases, a "name" check is the first thing in the sniff code or else such a check was done at a later point in the code.
This makes using the `Tokens::$functionNameTokens` array highly inefficient, as the _only_ token within that array which could have the "name" the sniff is looking for is `T_STRING`. The other eleven (!) tokens registered would **never** match and would never trigger an error, but would be passed to the …
> Performance: more selective sniffing for efficiency

- README.md
- composer.json
As VIPCS requires two external standards, including the new `VariableAnalysis` dependency, let's require the DealerDirect plugin to make life easier on people who install via Composer.
Includes updating the Readme to mention the `VariableAnalysis` standard, as well as mention that the DealerDirect plugin is now a project requirement.
Note: I've widened the version constraints for the DealerDirect plugin to prevent conflicts with customer projects which already required the plugin, but potentially at a different version.
The version constraints now set covers all released versions which support external standards properly.
> Composer: require the DealerDirect plugin

- WordPressVIPMinimum/Tests/Hooks/AlwaysReturnInFilterUnitTest.inc
- WordPressVIPMinimum/Tests/Hooks/AlwaysReturnInFilterUnitTest.php
... as an upstream PR containing a bug fix for the tokenizer issue this test documents has been merged.
Ref:
* squizlabc/PHP_CodeSniffer#3066
> Hooks/AlwaysReturnInFilter: adjust expectations for a test

- WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php
- WordPressVIPMinimum/Tests/Files/IncludingNonPHPFileUnitTest.inc
- WordPressVIPMinimum/Tests/Files/IncludingNonPHPFileUnitTest.php
This PR is the result of a full review of the `WordPressVIPMinimum.Files.IncludingNonPHPFile` sniff.
It will be easiest to understand the different changes and their impact by reviewing this PR on the individual commits.
Fixes #515
* Move the extensions against which checks are being run to private properties.
* Removes the `.` from the part in the regex which is being remembered.
Note: The `.` before the extension is still required, it is just no longer _remembered_.
* Changes the extension checks from using the relatively expensive `in_array()` to the lightweight `isset()`.
The regex will work just the same without the `.*`.
* The existing unit tests only tested against `require_once` and `include`, while the sniff looks for all variations.
The newly added unit tests make sure that all …
> Files/IncludingNonPHPFile: various improvements

- WordPressVIPMinimum/Sniffs/Constants/ConstantStringSniff.php
- WordPressVIPMinimum/Tests/Constants/ConstantStringUnitTest.inc
- WordPressVIPMinimum/Tests/Constants/ConstantStringUnitTest.php
> ConstantStringSniff: Take into account namespace prefixing

- WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php
- WordPressVIPMinimum/Tests/Performance/WPQueryParamsUnitTest.inc
- WordPressVIPMinimum/Tests/Performance/WPQueryParamsUnitTest.php
Note: I've split this change into two commits to allow for moving the second commit to the 3.0.0 release if so desired.
---
This:
* Switches the `WordPressVIPMinimum.Performance.WPQueryParams` sniff over to use the WordPressCS `AbstractArrayAssignmentRestrictionsSniff` as the parent sniff.
* Adds sniffing for the `exclude` array key via the `AbstractArrayAssignmentRestrictionsSniff` sniff logic.
Includes unit test.
Fixes #369
This changes over the existing keys being sniffed for by this sniff to use the logic from the new `AbstractArrayAssignmentRestrictionsSniff` parent instead of custom logic.
Note: this is a BC-break as the error codes for the existing checks change!
* `WordPressVIPMinimum.Performance.WPQueryParams.PostNotIn` is now …
> WPQueryParams: sniff for `exclude` array key being set

- WordPressVIPMinimum/Sniffs/Security/UnderscorejsSniff.php
- WordPressVIPMinimum/Tests/Security/Gruntfile.js
- WordPressVIPMinimum/Tests/Security/UnderscorejsUnitTest.inc
- WordPressVIPMinimum/Tests/Security/UnderscorejsUnitTest.js
- WordPressVIPMinimum/Tests/Security/UnderscorejsUnitTest.php
Result of a review of the `WordPressVIPMinimum.Security.Underscorejs` sniff.
Not claiming completeness as JS, like PHP, can be written in lots of different ways - think ternaries, method chaining etc - and my JS is a bit rusty ;-).
Consider this a first round of improvements.
Input regarding underscores syntaxes based on:
* https://www.topjavatutorial.com/underscore-js/underscore-js-escape-unescape-functions/
* https://underscorejs.org/
* https://devdocs.io/underscore/index
* https://stackoverflow.com/questions/4778881/how-to-use-underscore-js-as-a-template-engine
Code samples largely based on samples found via:
* https://wpdirectory.net/search/01EN00V6N7CVNF8SXDW6EA91NV
* https://wpdirectory.net/search/01EN00VG3ERYZ2BZZ5VFFZ62N4
* https://wpdirectory.net/search/01EN375V8PHQYTZB9T39VB9X6R …
> Security/Underscorejs: bug fixes and enhancements

- WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php
- WordPressVIPMinimum/Tests/Functions/DynamicCallsUnitTest.inc
- WordPressVIPMinimum/Tests/Functions/DynamicCallsUnitTest.php
This PR is the result of a review of the `WordPressVIPMinimum.Functions.DynamicCalls` sniff.
It will be easiest to understand the different changes and their impact by reviewing this PR on the individual commits.
---
... to show which ones should fail and which should pass.
This sniff only listens to `T_VARIABLE` tokens, so checking that what was received is a `T_VARIABLE` is redundant.
The condition above checks if a token is `T_EQUAL` and bows out if it is not.
The only code matching on `T_EQUAL` is the `=` operator, which will always have a `length` of `1`.
* Cutting code lines off at 50 chars is maybe taking it a little too far, especially as it makes assignments hard to read.
* Use proper tags in docblocks.
* Improve (fix) documentation (and move it to the right place).
Join two …
> Functions/DynamicCalls: various bug fixes and improvements

- WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php
In succession of #592 and alongside core vocabulary changes for more inclusiveness, I think we should rename the private variable to be a little more descriptive and use the word "disallowed" in place of "blacklist".
> Functions/DynamicCalls: Remove the word "blacklisted" and use "disallowed"

- WordPressVIPMinimum/ruleset.xml
We don't need two references of `WordPress.WP.AlternativeFunctions.curl_curl_getinfo` in the `WordPressVIPMinimum` ruleset.
> Remove second reference of WordPress.WP.AlternativeFunctions.curl_curl_getinfo

- WordPress-VIP-Go/ruleset.xml
Removing the cruft of declaring it as a warning since it is already one in the parent sniff:
https://github.com/WordPress/WordPress-Coding-Standards/blob/c52e511356c65c7ee97587dcb84e98b2f90e9633/WordPress/Sniffs/WP/AlternativeFunctionsSniff.php#L129-L143
> Removing cruft since it is already a warning in WordPress.WP.AlternativeFunctions.file_system_read

- WordPress-VIP-Go/ruleset.xml
> Remove warning type since it inherits from parent as "warning" 

- WordPress-VIP-Go/ruleset-test.inc
- WordPress-VIP-Go/ruleset.xml
> WordPress.Security.NonceVerification.NoNonceVerification: Remove outdated reference from WordPress-VIP-Go ruleset and let inheritance from parent

- README.md
- WordPress-VIP-Go/ruleset-test.php
- WordPress-VIP-Go/ruleset.xml
- WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
- WordPressVIPMinimum/Sniffs/Hooks/RestrictedHooksSniff.php
- WordPressVIPMinimum/Sniffs/Performance/NoPagingSniff.php
- WordPressVIPMinimum/Sniffs/Performance/OrderByRandSniff.php
- WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php
- WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php
- WordPressVIPMinimum/Sniffs/Variables/RestrictedVariablesSniff.php
- WordPressVIPMinimum/ruleset-test.php
- WordPressVIPMinimum/ruleset.xml
Since a lot of these links are outdated or redirecting, it would be best to have the accurate links in VIP Go context.
> Update doc links to docs.wpvip.com and remove WordPress.com refs

- WordPress-VIP-Go/ruleset.xml
> WordPress-VIP-Go: Replace WordPress.WP.GlobalVariablesOverride.OverrideProhibited with WordPress.WP.GlobalVariablesOverride.Prohibited

- WordPress-VIP-Go/ruleset.xml
- WordPressVIPMinimum/ruleset.xml
> Silence VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable

- WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
PR #450 deprecated the VIPCS native VariableAnalysis sniff in favour of using the upstream `VariableAnalysis` standard.
While the `process()` method - after throwing deprecation notices - would correctly hand off to the `parent::process()` method to let the upstream sniff handle throwing the errors, the `register()` method did not defer to the parent method.
This meant that the sniff would only listen to the original tokens the VIPCS native sniff was previously listening too and process those.
At the time of the switch-over, the tokens the VIPCS sniff was listening to and the tokens the VA sniff was listening to, happened to be the same.
However, in the mean time, in particularly in the VA `2.10.0` release, the tokens the VA sniff is listening to have been updated, while the VIPCS sniff …
> CI: fix test failure for the VIPCS VariableAnalysis sniff

- WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
- WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
- WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
- WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php
- WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php
- WordPressVIPMinimum/Sniffs/Performance/RegexpCompareSniff.php
- WordPressVIPMinimum/Sniffs/Performance/RemoteRequestTimeoutSniff.php
- WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
- WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php
- WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
- tests/RulesetTest.php
... picked up along the way.
Fixes:
* A few typos.
* Alignment of parameter descriptions.
* Wrong example code for some sniffs implementing an abstract sniff.
* A warning about commented out code which would start showing once PHPCS 3.6.0 will be released.
> Documentation: various minor improvements

- WordPress-VIP-Go/ruleset-test.inc
- WordPressVIPMinimum/ruleset-test.inc
Follow up on PR #618: update the inline comments in the ruleset test to match the new reality.
> Ruleset tests: minor updates

- WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php
- WordPressVIPMinimum/Tests/Files/IncludingFileUnitTest.inc
- WordPressVIPMinimum/Tests/Files/IncludingFileUnitTest.php
We're just doing an atomic commit for this one to solve #407 in reducing false positives.
However, the entire IncludingFileSniff needs a facelift with some breaking changes, so the work started in #626 will continue.
> IncludingFileSniff: add property of custom keywords to not trigger sniff

- WordPress-VIP-Go/ruleset-test.inc
- WordPress-VIP-Go/ruleset-test.php
- WordPress-VIP-Go/ruleset.xml
> Silence WordPress.WP.AlternativeFunctions.file_system_read_fclose

- WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
- WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.inc
- WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.php
Fixes #155.
Also replaced "NOK" in the test with "Error" since "NOK" is harder to distinguish from "OK".
> ProperEscapingFunction: Flag when esc_attr is being used outside of HTML attributes

- WordPress-VIP-Go/ruleset-test.php
- WordPressVIPMinimum/ruleset-test.inc
- WordPressVIPMinimum/ruleset-test.php
- tests/RulesetTest.php
... and make two others more specific.
These ignore annotations have become redundant due to a combination of changes to the rulesets and upstream fixes.
> QA: remove redundant PHPCS ignore annotations

- WordPressVIPMinimum/Sniffs/Performance/LowExpiryCacheTimeSniff.php
- WordPressVIPMinimum/Tests/Performance/LowExpiryCacheTimeUnitTest.php
Issue reported by @GaryJones in https://github.com/Automattic/VIP-Coding-Standards/issues/628#issuecomment-790653774
In rare cases, it is possible that the call to `eval()` with "safe" tokens only, would still result in a parse error.
An example of such a case is when the PHP 5.6 `**` (`T_POW`) operator is used. PHPCS backfills the tokenization, which means that the operator is correctly recognized by the sniff as a "safe" token to use in the `eval()` statement.
However, when the sniff is being run on PHP 5.4/5.5, the `eval()` will also be run on PHP 5.4/5.5 and while PHPCS backfills the token, PHP does not, resulting in a parse error in the `eval`-ed code, upon which the `eval()` will return `false`.
This commit:
* Silences the parse error notice.
* Checks the output of the `eval()` for …
> LowExpiryCacheTime: improve handling of potential parse errors in eval-ed code

- .github/workflows/basics.yml
- .github/workflows/test.yml
- bin/php-lint
- composer.json
This installs two additional PHP packages in `require-dev`:
* [`php-parallel-lint`](https://packagist.org/packages/php-parallel-lint/php-parallel-lint) which allows for linting PHP files in parallel (faster), as well as automatically recursively walking directories.
* [`php-console-highlighter`](https://packagist.org/packages/php-parallel-lint/php-console-highlighter) which provides PHP code highlighting in the command line console, allowing the linter to display the results in a more meaningful manner.
It also adjusts the existing `bin/php-lint` script to use this new dependency instead of using *nix specific commands.
As it was, PHP linting was only done on PHP 7.4 as part of the `basics` workflow.
This commit changes this to run linting on the lowest (PHP 5.4) and highest (latest/PHP …
> GH Actions: switch over to parallel linting of PHP files

- .github/workflows/basics.yml
- composer.json
The `phpcsstandards/phpcsdevtools` package includes a script which can check whether sniffs are feature complete, i.e. whether all sniffs have unit tests and documentation.
By adding this check to the `basics` GH Actions workflow, we prevent untested and/or undocumented sniffs from entering the repo.
For now, the documentation check is silenced.
P.S.: the `PHPCSDevTools` package contains a few more goodies which having the package (dev-)required now make available to developers, like the `PHPCSDebug` standard to get detailed information about the tokens in a file.
Have a look at the package [readme](https://github.com/PHPCSStandards/PHPCSDevTools) for more information.
Related to #628
> GH Actions: always check that all sniffs are feature complete

- .github/workflows/quicktest.yml
- .github/workflows/test.yml
The "quicktest" stage will basically run the same tasks as the "test" workflow (linting, unit tests and the ruleset tests), but only against low/high PHP/PHPCS/WPCS combinations. This should catch most issues.
This "quicktest" stage will run for pushes and for merges to `develop`.
The more comprehensive complete build against a larger set of PHP/PHPCS/WPCS combinations will now only be run on PRs and merges to `master`.
Related to #628
> GH Actions: add "quicktest" stage for non-PR/merge builds

- CHANGELOG.md
Minor tweak for readability and usability.
> Changelog: minor tweak

- WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
- WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.inc
As part of the changes made in #624, the `T_COMMA` token was added to the list of tokens to skip over, to allow for `echo` statements with multiple arguments passed as a coma-delimited list.
As a side-effect, this caused the sniff to also examine `[s]printf()`-like function calls where the first parameter is a text string, while the second is often a variable within a call to one of the escaping functions.
The current change fixes this by only adding the `T_COMMA` token to the "ignore when looking for the previous token"-list when in an `echo` statement.
Includes unit test.
Fixes #667
Additional notes:
* I've run the sniff over WP Core to verify the fix and have verified that all 23 violations being throw up are correctly detected violations.
* If it would be considered a good idea to …
> ProperEscapingFunction: fix overreach

- WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
- WordPressVIPMinimum/Tests/Security/ProperEscapingFunctionUnitTest.inc
Prior to VIPCS 2.3.0, equal signs not followed by quotes were ignored by this sniff, even though unquoted values for attributes in HTML is supported as long as the value does not contain whitespace.
However, detecting equal signs not followed by quotes could confuse the attribute detecting as equal signs without quotes can also be used outside of HTML attribute context.
This improves the attribute detection further by making sure that an equal sign (with or without subsequent quotes) is preceded by at least one alphanumeric character to indicate it _could_ be an HTML attribute.
Includes tests.
Fixes #680
> ProperEscapingFunction: further improve attribute matching

- WordPress-VIP-Go/ruleset.xml
This patch will configure `VariableAnalysis` for `WordPress-VIP-Go` so not to report on undefined variables under certain circumstances. To quote [an issue reported](https://github.com/Automattic/vip-go-ci/issues/120) for `vip-go-ci`:
> When template partials are require'd from within a class, then the partial may use $this->... to insert display a value. At PHP runtime, it works, but for PHPCS analysis, it sees a PHP file with an undefined $this and so reports it via the VariableAnalysis package. Technically it's correct, and while it could be ignored, it's not practical or desirable to do that.
This patch will accomplish this, reducing noise a bit for our end-users.
See [here for more discussion](https://github.com/Automattic/vip-go-ci/issues/120).
The following code was put into a …
> Update WordPress-VIP-Go/ruleset.xml to configure VariableAnalysis

- composer.json
As per https://github.com/Automattic/VIP-Coding-Standards/pull/690#issuecomment-864321421, we want to bump VA to include the recent fixes.
> Bump VA to 2.11.1

- .gitignore
- .phpcs.xml.dist
... to allow for faster scan results when scanning the VIPCS repo code itself.
The cache will automatically be invalidated when anything which is relevant changes.
> PHPCS: enable caching

- .github/workflows/basics.yml
- .github/workflows/quicktest.yml
- .github/workflows/test.yml
- composer.json
The `dealerdirect/phpcodesniffer-composer-installer` Composer plugin is used to register external PHPCS standards with PHPCS.
As of Composer 2.2.0, Composer plugins need to be explicitly allowed to run. This adds the necessary configuration for that.
Refs:
* https://blog.packagist.com/composer-2-2/#more-secure-plugin-execution
... for bridging differences in `E_ALL` across PHP versions.
Previously, in Travis, when the same branch was pushed again and the "Auto cancellation" option on the "Settings" page had been turned on (as it was for most repos), any still running builds for the same branch would be stopped in favour of starting the build for the newly pushed version of the branch.
To enable this behaviour in GH Actions, a `concurrency` configuration needs to be added to each workflow …
> CI: various updates

- .github/workflows/basics.yml
- .github/workflows/quicktest.yml
- .github/workflows/test.yml
A number of predefined actions have had major release, which warrant an update the workflow(s).
These updates don't actually contain any changed functionality, they are mostly just a change of the Node version used by the action itself (from Node 14 to Node 16).
Refs:
* https://github.com/actions/checkout/releases
> GH Actions: version update for various predefined actions

- bin/php-lint
- composer.json
PHP Console Highlighter has released version `1.0.0` and PHP Parallel Lint version `1.3.2` is the first PHP Parallel Lint version which supports PHP Console Highlighter `1.0.0`.
As the minimum supported PHP version is still PHP 5.3 for both, we can safely update both dependency requirements.
Refs:
* https://github.com/php-parallel-lint/PHP-Console-Highlighter/releases/tag/v1.0.0
* https://github.com/php-parallel-lint/PHP-Parallel-Lint/releases/tag/v1.3.2
While rare, there are some deprecations which PHP can show when a file is being linted.
By default these are ignored by PHP-Parallel-Lint.
Apparently though, there is an option to show them (wasn't documented until recently), so let's turn that option on.
> Composer: update PHP Parallel Lint and Console Highlighter

- composer.json
As per https://getcomposer.org/doc/04-schema.md#keywords by including "static analysis", then later versions of Composer will prompt users if the package is installed with `composer require` instead of `composer require-dev`.
> Update composer.json keywords

- WordPressVIPMinimum/Sniffs/Performance/OrderByRandSniff.php
This updates an outdated link to VIP's Documentation related errors reported by the use of `ORDER BY RAND()`. 
This issue was [reported in Slack](https://a8c.slack.com/archives/C245KEKF1/p1663012529865339).
> Updated Docs link for ORDER BY RAND()

- .github/workflows/quicktest.yml
- .github/workflows/test.yml
GitHub has deprecated the use of `set-output` (and `set-state`) in favour of new environment files.
This commit updates workflows to use the new methodology.
Refs:
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
👉🏻 Note: this won't get rid of all warning yet as a lot of predefined action runners also use set-output, but most of those are in the process of updating and/or have released a new version already, so the other warnings should automatically disappear over the next few weeks.
> GH Actions: fix use of deprecated `set-output`

- .github/workflows/basics.yml
The `xmllint-problem-matcher` action runner has released a new version which updates it to use node 16. This gets rid of a warning which was shown in the action logs.
Note: I've [suggested to the author to use long-running branches for the action runner instead](https://github.com/korelstar/xmllint-problem-matcher/pull/7), which would make this update redundant, but no telling if or when they'll respond to that, let alone if they will follow my suggestion.
Refs:
* https://github.com/korelstar/xmllint-problem-matcher/releases/tag/v1.1
> GH Actions: update the xmllint-problem-matcher

- .github/workflows/basics.yml
As the `korelstar/xmllint-problem-matcher` repo now has a long-running `v1` branch, this update which was included in PR #725 is no longer needed (and would necessitate more frequent updates if it would remain).
Ref:
* korelstar/xmllint-problem-matcher#7
If there is a ruleset error, the `cs2pr` action doesn't receive an `xml` report and exits with a `0` error code, even though the PHPCS run failed (though not on CS errors, but on a ruleset error).
This changes the GH Actions workflow to allow for that situation and still fail the build in that case.
> GH Actions: various tweaks

- .github/workflows/basics.yml
- .github/workflows/quicktest.yml
- .github/workflows/test.yml
Caches used in GH Actions do not get updated, they can only be replaced by a different cache with a different cache key.
Now the predefined Composer install action this repo is using already creates a pretty comprehensive cache key:
> `ramsey/composer-install` will auto-generate a cache key which is composed of
the following elements:
> * The OS image name, like `ubuntu-latest`.
> * The exact PHP version, like `8.1.11`.
> * The options passed via `composer-options`.
> * The dependency version setting as per `dependency-versions`.
> * The working directory as per `working-directory`.
> * A hash of the `composer.json` and/or `composer.lock` files.
This means that aside from other factors, the cache will always be busted when changes are made to the (committed) `composer.json` or the …
> GH Actions: bust the cache semi-regularly

- WordPressVIPMinimum/Tests/UserExperience/AdminBarRemovalUnitTest.inc
The `// phpcs:set` comment should be a PHP comment, but the PHP opening delimiter was missing.
> AdminBarRemovalUnitTest: Ensure final reset is read

- .github/workflows/quicktest.yml
- .github/workflows/test.yml
- bin/unit-tests
While the different logic for PHP 8.1 was in the GitHub workflow, moving it to the bin script means the GitHub workflow can be simplified, and the same Composer script can be run locally too.
> Unit tests: Support PHP >= 8.1

- WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
- WordPressVIPMinimum/Sniffs/Compatibility/ZoninatorSniff.php
- WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
~**Once #732 has been merged, this can be rebased** to just show coding standards changes.~
----
Update the VIPCS sniffs to fix the coding standards changes with WPCS 3.0.
Slightly better performance.
Using named parameters with a variable named `$string` is unfavourable.
~WordPress-Extra will no longer use the `Generic.Arrays.DisallowShortArraySyntax` rule, but does use the improved `Universal.Arrays.DisallowShortArraySyntax` from PHPCSExtra instead, so whilst we have short array syntax being used in the VIPCS sniffs, let's continue to exclude the rule.~
> WPCS 3.0: Fix coding standards of VIPCS sniffs

- .github/workflows/basics.yml
- .github/workflows/quicktest.yml
- .github/workflows/test.yml
- README.md
- composer.json
Add support for PHP 8.1 features, including fixing a retokenization of reserved keywords bug in PHPCS 3.7.0.
With a new minimum version of PHPCS, this allows consolidation and simplification of the testing matrix in the `test.yml` workflow.
I'd like to get this into 2.3.4, but this may be semantically better for 3.0.0?
> Composer: up the minimum PHPCS version to 3.7.1

- .github/workflows/quicktest.yml
- .github/workflows/test.yml
Turn on display_errors for quicktest, and separate out PHPCS and WPCS composer requires into separate steps.
> CI: test and quicktest tweaks

- WordPressVIPMinimum/Sniffs/Performance/NoPagingSniff.php
- WordPressVIPMinimum/Sniffs/Performance/OrderByRandSniff.php
- WordPressVIPMinimum/Sniffs/Performance/RegexpCompareSniff.php
- WordPressVIPMinimum/Sniffs/Performance/RemoteRequestTimeoutSniff.php
- WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php
The WPCS `AbstractArrayAssignmentRestrictionsSniff` expects an array from `getGroups()` which includes a `'message'` key.
The `callback()` method subsequently allows to override that message with a higher priority message if needed in specific circumstances.
None of these sniffs, however, have a need to override the message, so the `callback()` method can just use the default behaviour of returning `true` or `false` and use the `'message'` as declared in the group.
... from these same sniffs. These comments are copy/paste documentation from the abstract and not specific to the actual sniff.
> Some simplifications of sniffs extending the WPCS `AbstractArrayAssignmentRestrictionsSniff`

- WordPressVIPMinimum/Sniffs/Performance/RegexpCompareSniff.php
This condition will always be `true` if one of the previous conditions is `true`, so is redundant.
> Performance/RegexpCompare: remove redundant condition

- .github/workflows/basics.yml
- .github/workflows/quicktest.yml
- .github/workflows/test.yml
... of the bash `date` command in the earlier pulled cache busting.
Removes the `experimental` key from the matrix as we can just use a plain comparison in the `continue-on-error` key.
> GH Actions: 2 minor simplification

- WordPress-VIP-Go/ruleset.xml
- WordPressVIPMinimum/ruleset.xml
While looking into #588, I noticed something which seemed odd, so I'm addressing this with this PR.
The configuration which was added in #690 (and addressed #588) was added to the `WordPress-VIP-Go` ruleset, not the `WordPressVIPMinimum` ruleset from which the `WordPress-VIP-Go` ruleset inherits.
I can not think of any pertinent reason why the configuration should be added for one, but not the other and I couldn't find any discussion on this either, so I propose moving the configuration from the `WordPress-VIP-Go` ruleset to the `WordPressVIPMinimum` ruleset.
Ref: https://github.com/sirbrillig/phpcs-variable-analysis/releases/tag/v2.9.0
> Rulesets: move VariableAnalysis configuration from Go to Minimum

- WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
The `$functionList` property is only ever written to, never _read_, so all that work walking all the tokens in the complete class scope is redundant (and was done in a highly inefficient way in the first place).
So, removing all code related to the property should improve performance of the sniff a little.
> Classes/DeclarationCompatibility: remove redundant code

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- WordPressVIPMinimum/Sniffs/AbstractVariableRestrictionsSniff.php
- WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
- WordPressVIPMinimum/Sniffs/Constants/ConstantStringSniff.php
- WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php
- WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php
- WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
- WordPressVIPMinimum/Sniffs/Hooks/PreGetPostsSniff.php
- WordPressVIPMinimum/Sniffs/Performance/LowExpiryCacheTimeSniff.php
- WordPressVIPMinimum/Sniffs/Security/ProperEscapingFunctionSniff.php
- WordPressVIPMinimum/Sniffs/Security/UnderscorejsSniff.php
- WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php
- WordPressVIPMinimum/ruleset.xml
- composer.json
- tests/bootstrap.php
By starting to use PHPCSUtils, we make VIPCS less dependent on WordPressCS. It has brings added benefits of more stable, thoroughly tested utility methods, which all support modern PHP.
This adds the dependency and updates relevant documentation.
**Note**: I've _not_ changed the GH Actions workflows to add PHPCSUtils to the matrix (yet). Changes to the workflows will be done in a separate commit.
PHPCSUtils does not contain any sniffs, so adding this rule isn't strictly necessary, but by having the rule in the ruleset anyway, if PHPCSUtils is missing, the user will get a descriptive error message during the loading of the ruleset instead of a fatal "class not found" error once the sniffs start running.
Adding this only in the `WordPressVIPMinimum` ruleset is sufficient as the …
> 3.0: start using PHPCSUtils

- WordPressVIPMinimum/Sniffs/Constants/RestrictedConstantsSniff.php
- WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php
- WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php
- WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
- WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
- WordPressVIPMinimum/Sniffs/JS/DangerouslySetInnerHTMLSniff.php
- WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php
- WordPressVIPMinimum/Sniffs/JS/InnerHTMLSniff.php
- WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php
- WordPressVIPMinimum/Sniffs/JS/StrippingTagsSniff.php
- WordPressVIPMinimum/Sniffs/JS/WindowSniff.php
- WordPressVIPMinimum/Sniffs/Performance/CacheValueOverrideSniff.php
- WordPressVIPMinimum/Sniffs/Performance/FetchingRemoteDataSniff.php
- WordPressVIPMinimum/Sniffs/Performance/TaxonomyMetaInOptionsSniff.php
- WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php
- WordPressVIPMinimum/Sniffs/Security/EscapingVoidReturnFunctionsSniff.php
- WordPressVIPMinimum/Sniffs/Security/ExitAfterRedirectSniff.php
- WordPressVIPMinimum/Sniffs/Security/StaticStrreplaceSniff.php
- WordPressVIPMinimum/Sniffs/Sniff.php
- WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php
What with more `use` statements coming in now with PHPCSUtils and WPCS 3.0, it made sense to create some order in these.
> CS: improve use statements

- WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php
This commit removes the custom token target + custom logic from this sniff in favour of deferring to the logic in the parent sniff - as discussed in #589.
To that end, the keys which were handled in the custom `process_token()` logic have now been added to the `getGroups()` array.
As the logic for whether or not an error message should be thrown is different for each group, an extra `'name'` key has been added to each group to allow the `callback()` function to distinguish what group the detected key came from.
It also updates the error message being used to better cover both keys being looked for, as well as mention this only applies when the array is passed to `get_posts()` (in an attempt to remove some of the confusion reported in #672).
Note: this is a BC-break as the error codes for …
> Performance/WPQueryParams: defer to the parent sniff

- WordPressVIPMinimum/Tests/Performance/NoPagingUnitTest.inc
- WordPressVIPMinimum/Tests/Performance/NoPagingUnitTest.php
Safeguard the fix which was added to WPCS 3.0.0 in response to WPCS issue WordPress/WordPress-Coding-Standards #2211, which was created to handle VIPCS issue #713.
> Performance/NoPaging: add extra tests

- WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php
Given that:
* `$insideIfConditionalReturn` has a default value of `0`;
* And that value is only ever increased;
* The `$insideIfConditionalReturn >= 0` condition will always be `true`.
So this condition can be safely removed, just like the - now unused - assignments to the variable.
The original condition was introduced with the introduction of the sniff in #177. The condition was adjusted in #291, which made the logic redundant.
Looking at the sniff, I believe the intention was to only flag the "return outside condition missing" when not all control structure paths had a `return` statement, but this was never really properly checked as the only control structures taken into account are `if` control structures.
I believe it would be good to improve the sniff to handle more control …
> Hooks/AlwaysReturnInFilter: remove redundant condition

- WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php
- WordPressVIPMinimum/Tests/Performance/WPQueryParamsUnitTest.inc
- WordPressVIPMinimum/Tests/Performance/WPQueryParamsUnitTest.php
As reported in #672 and #729, the `get_users()` function also takes an array parameter which takes an `'exclude'` key. That key is not our target, so should not be flagged.
This commit adds a hard-coded exception specifically for that situation.
If at a later point in time, more situations which need exceptions would be discovered, this solution can be made more flexible, but for now, there is no need (or insight into where the flexibility should be).
As the `AbstractArrayAssignmentRestrictionsSniff::callback()` method does not have access to the `$stackPtr`, the logic which can be used in the `callback()` is limited. Also see the review notes from upstream WordPress/WordPress-Coding-Standards#2266, which basically already pointed out this exact problem.
To get round this, I'm overloading …
> Performance/WPQueryParams: prevent false positives for 'exclude' with get_users()

- .gitattributes
- .github/workflows/basics.yml
- .gitignore
- phpstan.neon.dist
PHPStan is a good addition to our QA toolkit and with improvements PHPStan has made over the years is now a viable tool for us to use (previously it would give way too many false positives).
This commit:
* Adds a separate job to the `basics` workflow in GH Actions.
Notes:
- I've chosen **not** to add PHPStan to the Composer dependencies for two reasons:
1. It doesn't allow for installation on PHP < 7.2, which would break/block the `composer install` for our test runs.
2. It would add dependencies which could conflict/cause problems for our test runs due to those defining token constants too.
- We could potentially use [Phive](https://phar.io/) to still have a setup which can be used locally, but just running locally from a PHPStan PHAR file should work just fine.
- For CI, PHPStan will be …
> Add PHPStan to QA checks

- .github/workflows/quicktest.yml
- .github/workflows/test.yml
VIPCS now doesn't just have PHPCS and WPCS as dependencies for the sniffs and ruleset tests, but also PHPCSUtils, PHPCSExtra and VariableAnalysis and for those last three, the different versions which may be supported are not (yet) taken into account.
Now, it could be argued that every single combination of the different versions of each of these dependencies should be tested, but that would make the matrix _huge_ to little added benefit.
So, instead I'm proposing a slightly different strategy, which should still allow us to verify that things work correctly with enough confidence, while making the workflow maintenance less involved.
The change I'm proposed in this commit takes advantage of the Composer `--prefer-lowest` option to achieve this.
It basically sets the matrix up to test …
> GH Actions: tweak the way the PHPCS/WPCS versions are set

- WordPressVIPMinimum/Sniffs/Security/MustacheSniff.php
- WordPressVIPMinimum/Tests/Security/MustacheUnitTest.inc
As reported in [541#issuecomment-1692323177](https://github.com/Automattic/VIP-Coding-Standards/issues/541#issuecomment-1692323177).
This commit fixes the issue + adds a test to safeguard the fix.
> Security/Mustache: prevent false positives on block editor templates

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/release-template.md
- .github/workflows/quicktest.yml
- .github/workflows/test.yml
:warning: **_Opening in draft in anticipation of the branch rename. The PR should not be merged until the branch rename has been executed (just before the release)._** ⚠️ 
Closes #666
> Updates related to branch rename from master to main

- .github/ISSUE_TEMPLATE/bug_report.md
Noticed this while having a quick look through the release PR. As this is not a file which is included in the release (`export-ignore`d via `.gitattributes`), I'm pulling this to `develop`.
> Issue template: mention PHPCSExtra

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/release-template.md
- .github/workflows/quicktest.yml
- .github/workflows/test.yml
- CHANGELOG.md
- phpunit.xml.dist
> Merge release/3.0.0 into develop

- WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php
- WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.inc
- WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.php
While looking at this sniff for something unrelated, I started wondering if the signature definitions were still in line with WP Core.
Turned out they were not, though with the current checks being done in the sniff, this wasn't necessarily problematic (though it should have been, but that's for another PR).
Also see the [additional notes I've added to the review ticket](https://github.com/Automattic/VIP-Coding-Standards/issues/507#issuecomment-1724805522).
Refs:
* https://developer.wordpress.org/reference/classes/wp_widget/wp_widget/
* https://developer.wordpress.org/reference/classes/walker/start_el/
* https://developer.wordpress.org/reference/classes/walker/end_el/
* https://developer.wordpress.org/reference/classes/walker/unset_children/
> Classes/DeclarationCompatibility: sync with WP Core

- .github/CONTRIBUTING.md
- .phpcs.xml.dist
- LICENSE.md
- README.md
- WordPress-VIP-Go/ruleset.xml
- WordPressVIPMinimum/ruleset.xml
- composer.json
⚠️  **_This is a DRAFT PR on purpose as it references releases which have not yet been tagged. Once the PHPCS 3.8.0 tag is available ~~(which contains the Composer `replace` directive)~~ and the other dependencies have released, this can/should be merged ~~and released ASAP~~._** ⚠️ 
---
The Squizlabs repo has been abandoned. The project continues in a fork in the PHPCSStandards organisation.
Ref:
* squizlabs/PHP_CodeSniffer#3932
... for improved PHP 8.2 support.
~~... to prevent end-users from running into trouble with the name change.~~
~~The files in the Composer `vendor/bin` will only be replaced when the `replace...` directive is found and that is only available in the 3.8.0 tag.~~
~~When the files in the Composer `vendor/bin` are not replaced, they will continue to point to the …
> Switch to PHPCSStandards/PHP_CodeSniffer & raise minimum supported version

- .github/CONTRIBUTING.md
- .github/workflows/basics.yml
- .github/workflows/quicktest.yml
- .github/workflows/test.yml
- .gitignore
- bin/unit-tests
- composer.json
- phpstan.neon.dist
- phpunit.xml.dist
Follow up on #805
PHP_CodeSniffer 3.8.0 now allows for running the tests, which are based on the PHPCS native test suite, with PHPUnit 8 and 9.
This commit updates the package to take advantage of that.
Includes:
* Widening the PHPUnit version requirements.
* Adding the PHPUnit 8+ cache file to `.gitignore`.
* Updating the PHPUnit configuration to make sure that PHP deprecations will always show, even when on a high PHPUnit 9.6 version.
* Updating the info in `CONTRIBUTING`.
* Simplifications to the `quicktest` and `test` workflows. Also, the code coverage "high" run can now be run against PHP 8.3.
* Running PHPStan against PHP `latest` (couldn't previously be done due to the old PHPUnit version).
* Updating the `unit-tests` script to remove the PHP version based toggle, which is no …
> Tests: allow for PHPUnit 8/9

- .github/CONTRIBUTING.md
Follow up to #809 and #796
(sorry, only realized after the merge of #809 that I'd still made a small tweak, but hadn't pushed it up)
> CONTRIBUTING: minor tweak

- README.md
Update some old WPVIP Documentation links.
> Docs: Fix links

- CHANGELOG.md
Was a level 2 but should have been a level 3.
> Docs: Fix changelog heading

- .github/workflows/basics.yml
Okay, so apparently, there is a long-standing bug in the Microsoft package deploy process which caused `apt-get update` to fail in the first half hour after Microsoft has deployed a package.
The failure looks like this:
```
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
```
As this only happens intermittently (after a MS package deploy), the chance of running into this bug are slim, but guess what: today I ran into it.
This change to the workflow is intended to prevent the next person running into this issue from having to waste time on figuring this out.
By splitting the "Install xmllint" step into two steps: one doing the `apt-get update` and one doing the …
> GH Actions: work around intermittent apt-get errors
