WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php
CheckReturnValueSniff: allowing the function to be checked for multiple callees and adding check for checking get_the_terms and get_the_tags passed to foreach w/o checking the return value.
=> Syncing with SVN version

WordPressVIPMinimum/ruleset.xml
=> Add DontExtract sniff to the WordPressVIPMinimum ruleset

WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php
=> Add tests for internal VIP functions

WordPressVIPMinimum/ruleset.xml
=> Adding Generic.PHP.DisallowShortOpenTag to the ruleset

WordPressVIPMinimum/Sniffs/Cache/CacheValueOverrideSniff.php, WordPressVIPMinimum/Tests/Cache/CacheValueOverrideUnitTest.inc, WordPressVIPMinimum/Tests/Cache/CacheValueOverrideUnitTest.php
=> Adding sniff for catching cache overriding/disabling code

WordPressVIPMinimum/Sniffs/VIP/RegexpCompareSniff.php, WordPressVIPMinimum/Tests/VIP/RegexpCompareUnitTest.inc, WordPressVIPMinimum/Tests/VIP/RegexpCompareUnitTest.php
=> Fix 40/flag regexp compare

WordPressVIPMinimum/Sniffs/VIP/FlushRewriteRulesSniff.php, WordPressVIPMinimum/Tests/VIP/FlushRewriteRulesUnitTest.inc, WordPressVIPMinimum/Tests/VIP/FlushRewriteRulesUnitTest.php
=> Addnig sniff for catching `$wp_rewrite->flush_rules()` calls

WordPressVIPMinimum/Sniffs/Constants/ConstantRestrictionsSniff.php, WordPressVIPMinimum/Tests/Constants/ConstantRestrictionsUnitTest.inc, WordPressVIPMinimum/Tests/Constants/ConstantRestrictionsUnitTest.php
This PR also includes improvements on the sniff revealed by the unit tests.
=> Add unit tests for constant restrictions sniff and improve the sniff

WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php, WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.inc, WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.php
This PR also includes fixes for the sniff revealed by the unit tests.
=> Adding tests for declaration compatibility sniff and improve the sniff

WordPressVIPMinimum/Tests/Functions/CheckReturnValueUnitTest.php
There seems to be an extra expected error - there is no line 29 in the related .inc file
=> Fix CheckReturnValue unit test

.travis.yml, WordPressVIPMinimum/ruleset.xml, ruleset_test.inc, ruleset_test.php
=> Update ruleset to match recent upstream changes

WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.inc, WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.php, ruleset_test.inc, ruleset_test.php
It turned out, that the internal group has been broken for a while :(
=> Fix wpcom vip irc sniff

.gitignore, WordPressVIPMinimum/Sniffs/Actions/PreGetPostsSniff.php, WordPressVIPMinimum/Sniffs/Cache/CacheValueOverrideSniff.php, WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php, WordPressVIPMinimum/Sniffs/Constants/ConstantRestrictionsSniff.php, WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php, WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php, WordPressVIPMinimum/Sniffs/VIP/ErrorControlSniff.php, WordPressVIPMinimum/Sniffs/VIP/FlushRewriteRulesSniff.php, WordPressVIPMinimum/Sniffs/VIP/RegexpCompareSniff.php, WordPressVIPMinimum/Sniffs/VIP/RemoteRequestTimeoutSniff.php, WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisHelper.php, WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php, WordPressVIPMinimum/Tests/Actions/PreGetPostsUnitTest.php, WordPressVIPMinimum/Tests/Cache/CacheValueOverrideUnitTest.php, WordPressVIPMinimum/Tests/Classes/DeclarationCompatibilityUnitTest.php, WordPressVIPMinimum/Tests/Constants/ConstantRestrictionsUnitTest.php, WordPressVIPMinimum/Tests/Files/IncludingFileUnitTest.php, WordPressVIPMinimum/Tests/Functions/CheckReturnValueUnitTest.php, WordPressVIPMinimum/Tests/VIP/ErrorControlUnitTest.php, WordPressVIPMinimum/Tests/VIP/FlushRewriteRulesUnitTest.php, WordPressVIPMinimum/Tests/VIP/RegexpCompareUnitTest.php, WordPressVIPMinimum/Tests/VIP/RemoteRequestTimeoutUnitTest.php, WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.php, ruleset_test.php
The Variables/VariableAnalysisHelper and VariableAnalysisSniff files are being ignored, as they come from a different project and updating the styling would make future syncs really hard.
This commit also contians new .gitignore file.
=> Addressing all styling issues reported by PHPCS

WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php, WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.inc, WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php
=> Fix 78/properly reference phpcs file

WordPressVIPMinimum/ruleset.xml, ruleset_test.inc, ruleset_test.php
This commit also contains related changes to the integration tests
=> Adding Squiz.PHP.CommentedOutCode sniff to the ruleset

WordPressVIPMinimum/Sniffs/VIP/ExitAfterRedirectSniff.php, WordPressVIPMinimum/Tests/VIP/ExitAfterRedirectUnitTest.inc, WordPressVIPMinimum/Tests/VIP/ExitAfterRedirectUnitTest.php, ruleset_test.inc, ruleset_test.php
=> Report on missing exit after redirect

WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php, WordPressVIPMinimum/Tests/Files/IncludingFileUnitTest.inc
=> Ignore `locate_template` in IncludingFile sniff

WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.inc, WordPressVIPMinimum/Tests/VIP/RestrictedFunctionsUnitTest.php, ruleset_test.inc, ruleset_test.php
=> Adding is_multi_author function to restricted ones.

WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php, WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.inc
fixes #83 
Props @rheinardkorf
=> Don't report on undefined `$this` within Trait, similarly to class.

WordPressVIPMinimum/ruleset.xml
=> Ignore SuperfluousWhitespace in css and js files.

WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php, WordPressVIPMinimum/Tests/JS/StringConcatUnitTest.js, WordPressVIPMinimum/Tests/JS/StringConcatUnitTest.php
Per https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/
=> Initial pass on HTML string concatenation sniff.

WordPressVIPMinimum/Sniffs/JS/StrippingTagsSniff.php, WordPressVIPMinimum/Tests/JS/StrippingTagsUnitTest.js, WordPressVIPMinimum/Tests/JS/StrippingTagsUnitTest.php
Per: https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/
=> Adding sniff reporting on vulnerable tags stripping approach.

WordPressVIPMinimum/Sniffs/JS/InnerHTMLSniff.php, WordPressVIPMinimum/Tests/JS/InnerHTMLUnitTest.js, WordPressVIPMinimum/Tests/JS/InnerHTMLUnitTest.php
The sniff flags any usage of `.innerHTML` with passed variable in it.
=> Initial pass on the innerHMTL sniff.

WordPressVIPMinimum/PHPCSCompatibility.php
=> Fixing typo in comment in PHPCSCompatiblity.php file

WordPressVIPMinimum/Sniffs/Constants/ConstantStringSniff.php
=> Fix a misleading comment

WordPressVIPMinimum/Sniffs/Actions/PreGetPostsSniff.php, WordPressVIPMinimum/Sniffs/Cache/BatcacheWhitelistedParamsSniff.php, WordPressVIPMinimum/Sniffs/Cache/CacheValueOverrideSniff.php, WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php, WordPressVIPMinimum/Sniffs/Constants/ConstantRestrictionsSniff.php, WordPressVIPMinimum/Sniffs/Constants/ConstantStringSniff.php, WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php, WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php, WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php, WordPressVIPMinimum/Sniffs/JS/InnerHTMLSniff.php, WordPressVIPMinimum/Sniffs/VIP/ErrorControlSniff.php, WordPressVIPMinimum/Sniffs/VIP/EscapingVoidReturnFunctionsSniff.php, WordPressVIPMinimum/Sniffs/VIP/ExitAfterRedirectSniff.php, WordPressVIPMinimum/Sniffs/VIP/FlushRewriteRulesSniff.php, WordPressVIPMinimum/Sniffs/VIP/ProperEscapingFunctionSniff.php, WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPressVIPMinimum/Sniffs/VIP/WPQueryParamsSniff.php, WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php, WordPressVIPMinimum/ruleset.xml
=> use backticks around code elements; fix a few typos

WordPressVIPMinimum/Sniffs/Actions/PreGetPostsSniff.php, WordPressVIPMinimum/Sniffs/Cache/BatcacheWhitelistedParamsSniff.php, WordPressVIPMinimum/Sniffs/Cache/CacheValueOverrideSniff.php, WordPressVIPMinimum/Sniffs/Classes/DeclarationCompatibilitySniff.php, WordPressVIPMinimum/Sniffs/Constants/ConstantRestrictionsSniff.php, WordPressVIPMinimum/Sniffs/Constants/ConstantStringSniff.php, WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php, WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php, WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php, WordPressVIPMinimum/Sniffs/Functions/DynamicCallsSniff.php, WordPressVIPMinimum/Sniffs/JS/HTMLExecutingFunctionsSniff.php, WordPressVIPMinimum/Sniffs/JS/InnerHTMLSniff.php, WordPressVIPMinimum/Sniffs/JS/StringConcatSniff.php, WordPressVIPMinimum/Sniffs/JS/StrippingTagsSniff.php, WordPressVIPMinimum/Sniffs/Plugins/ZoninatorSniff.php, WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputMustacheSniff.php, WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputTwigSniff.php, WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputUnderscorejsSniff.php, WordPressVIPMinimum/Sniffs/TemplatingEngines/UnescapedOutputVuejsSniff.php, WordPressVIPMinimum/Sniffs/VIP/ExitAfterRedirectSniff.php, WordPressVIPMinimum/Sniffs/VIP/ProperEscapingFunctionSniff.php, WordPressVIPMinimum/Sniffs/VIP/RegexpCompareSniff.php, WordPressVIPMinimum/Sniffs/VIP/RemoteRequestTimeoutSniff.php, WordPressVIPMinimum/Sniffs/VIP/RestrictedFunctionsSniff.php, WordPressVIPMinimum/Sniffs/VIP/StaticStrreplaceSniff.php, WordPressVIPMinimum/Sniffs/VIP/TaxonomyMetaInOptionsSniff.php, WordPressVIPMinimum/Sniffs/Variables/ServerVariablesSniff.php, WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisHelper.php, WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php, ruleset_test.php
Inspired by #185 minus the changes to checks
=> PHPCS fixes

WordPress-VIP-Go/ruleset.xml
Move a few things that potentially won't work and needs a dev to review up to error level 6 from error level 5
=> Move rules around

WordPressVIPMinimum/Sniffs/Variables/ServerVariablesSniff.php, WordPressVIPMinimum/Tests/Variables/ServerVariablesUnitTest.inc, WordPressVIPMinimum/Tests/Variables/ServerVariablesUnitTest.php
Reverts Automattic/VIP-Coding-Standards#219 (need to fix TravisCI error)
=> Revert "Fix detection of double quotes, add additional server variables and u…"

WordPressVIPMinimum/Sniffs/Filters/AlwaysReturnSniff.php
=> fix spelling of "returning"

WordPress-VIP-Go/ruleset.xml, WordPressVIPMinimum/Sniffs/JS/DangerouslySetInnerHTMLSniff.php, WordPressVIPMinimum/Tests/JS/DangerouslySetInnerHTMLUnitTest.js, WordPressVIPMinimum/Tests/JS/DangerouslySetInnerHTMLUnitTest.php
=> Add new DangerouslySetInnerHTML sniff

WordPress-VIP-Go/ruleset.xml
=> Silence batcache for VIP Go ruleset

WordPress-VIP-Go/ruleset.xml, WordPressVIPMinimum/Sniffs/JS/WindowSniff.php, WordPressVIPMinimum/Tests/JS/WindowUnitTest.js, WordPressVIPMinimum/Tests/JS/WindowUnitTest.php
=> Add Window object Sniff for JS

WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.inc, WordPressVIPMinimum/Tests/Variables/VariableAnalysisUnitTest.php, WordPressVIPMinimum/ruleset.xml
Fixes #114. This is a reboot of #144.
=> Hide catching exceptions

WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
=> Remove incorrect severity level parameters since they are passed in a string

README.md
=> Docs: Updates Readme notes

WordPressVIPMinimum/Sniffs/VIP/RestrictedVariablesSniff.php
=> RestrictedVariablesSniff: Amend error message for session variable usage

WordPress-VIP-Go/ruleset.xml, WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
Silences on VIP Go. Fixes #259.
=> Add get_site_option and update_site_option to RestrictedFunctionsSniff

WordPressVIPMinimum/Sniffs/Classes/RestrictedExtendClassesSniff.php, WordPressVIPMinimum/Sniffs/Functions/CheckReturnValueSniff.php, WordPressVIPMinimum/Sniffs/JS/WindowSniff.php, WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
- Unused import
- Unused local variable
- Unused parameter
- Unused private field
See #349.
=> Inspection: Remove unused items

WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php, WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php
=> Inspection: Fix undefined classes

WordPressVIPMinimum/Sniffs/Compatibility/ZoninatorSniff.php
=> Inspection: Remove redundant self-assignment

WordPressVIPMinimum/Sniffs/Files/IncludingNonPHPFileSniff.php, WordPressVIPMinimum/Sniffs/Hooks/AlwaysReturnInFilterSniff.php, WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
=> Inspection: Fix assignment in condition

WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php, WordPressVIPMinimum/Sniffs/Variables/VariableAnalysisSniff.php
=> Inspection: Remove returning void function calls

WordPress-VIP-Go/ruleset-test.php, WordPress-VIP-Go/ruleset.xml
=> Remove ambiguous message in WordPress-VIP-Go ruleset for Generic.NamingConventions.ConstructorName.OldStyle

WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php
=> Remove empty default in switch statements

CHANGELOG.md, CONTRIBUTING.md
=> Docs: Add notes about Ruleset Tests

CHANGELOG.md
Adds the change log for all the changes between 0.4.0 and 1.0.0.
Do NOT merge, until the point where we're happy to release.
(After this release, we can switch to using a `git-flow` approach where all work is done against a `develop` branch, and so the merge to `master` is only done from a release branch.)
=> Change log: 1.0.0

README.md, WordPress-VIP-Go/ruleset-test.php, WordPress-VIP-Go/ruleset.xml, WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php, WordPressVIPMinimum/Sniffs/Hooks/RestrictedHooksSniff.php, WordPressVIPMinimum/Sniffs/Performance/NoPagingSniff.php, WordPressVIPMinimum/Sniffs/Performance/OrderByRandSniff.php, WordPressVIPMinimum/Sniffs/Performance/WPQueryParamsSniff.php, WordPressVIPMinimum/Sniffs/UserExperience/AdminBarRemovalSniff.php, WordPressVIPMinimum/ruleset.xml
=> Switch vip.wordpress.com to wpvip.com

CHANGELOG.md, CONTRIBUTING.md, README.md
Should be merged, and the commit tagged with `2.0.0`, and Release made, on Friday 12th July 2019.
=> Docs: change log for 2.0.0

WordPressVIPMinimum/Sniffs/Files/IncludingFileSniff.php, WordPressVIPMinimum/Tests/Files/IncludingFileUnitTest.inc, WordPressVIPMinimum/Tests/Files/IncludingFileUnitTest.php
=> IncludingFileSniff: Add get_parent_theme_file_path to safelist

.travis.yml, WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php
Tested at https://config.travis-ci.com/explore
=> Travis: rearrange, and fix warnings and infos

.github/CONTRIBUTING.md
Oops... that line isn't needed anymore. (Follow up on #501)
=> Contributing: remove duplicate info

CHANGELOG.md
❗ Reviews & approval welcome. I'll merge this myself (if approved) just before the release. ❗
Includes all currently merged changes.
Since we now have an external contributor (Juliette), then we can/should start giving props.
I also find it useful when other change logs give a link to the PR where I can start following the trail of what exactly the change was and why it was made, so I've added them in as well. By using full inline markdown link (rather than just `[#123]` inline and the `[#123]: https://…` at the bottom), then it makes the copy-paste into the Release notes cleaner.
=> Change log for VIPCS 2.2.0

WordPress-VIP-Go/ruleset.xml
Accidentally introduced in #620..
=> Remove extra tabs that snuck in the XML file

WordPress-VIP-Go/ruleset.xml
=> Silence WordPress.WP.AlternativeFunctions.file_system_read_readfile

.github/ISSUE_TEMPLATE/release-template.md
... just as a reminder.
Includes minor fix for improved markdown.
=> Release template: add checkbox for dependency check

.github/ISSUE_TEMPLATE/release-template.md
A good item to have before a release, props @jrfnl for the idea.
=> Docs: Add version compare for bugs to checklist

CHANGELOG.md
For all the lovely bugfixes that @jrfnl worked on.
=> Add changelog for 2.3.1 release

README.md
Follow up to #691
The required version of the VariableAnalysis package was no longer in sync with the actual requirement as per the `composer.json` file.
=> README: update requirements listing

CHANGELOG.md, README.md
The Composer plugin has a new home.
Ref: https://github.com/PHPCSStandards/composer-installer/issues/146
=> Update references to the Composer plugin

.github/workflows/basics.yml
Fix failing installation of the xmllint tooling.
=> GH Actions/CS: fix build failure

composer.json
Not sure how this didn't get caught before.
=> Composer: fix script references

.github/workflows/test.yml
=> CI: Test Higher PHP versions

.github/workflows/quicktest.yml, .github/workflows/test.yml
Only disregard an upper limit to the PHP restrictions.
=> GH Actions: minor tweaks to the composer options used

.github/CONTRIBUTING.md
Refresh the contributor documentation.
=> Docs: Update CONTRIBUTING.md

.github/workflows/basics.yml, .github/workflows/quicktest.yml, .github/workflows/test.yml
* Update a URL which is no longer valid.
* Ensure all steps have a name.
=> GH Actions: minor tweaks

WordPressVIPMinimum/Sniffs/Functions/RestrictedFunctionsSniff.php, WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.inc, WordPressVIPMinimum/Tests/Functions/RestrictedFunctionsUnitTest.php
=> Deprecate suggesting using wpcom_vip_get_page_by_path
